outlook:
  name: "Bob Example"
  user: "bob.example@hotmail.com"
  domain: "hotmail.com"
  ingoing:
    host: "outlook.office365.com"
    port: 993
  outgoing:
    host: "smtp-mail.outlook.com"
    port: 587
